# Generated by Django 3.0.10 on 2020-11-02 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peluqueria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('rut_cliente', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('id_usuario_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='estado_hora',
            fields=[
                ('if_estado_hora', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='estado_reserva',
            fields=[
                ('id_estado_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='fecha',
            fields=[
                ('id_fecha', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='horas_peluqueria',
            fields=[
                ('id_hora', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_inicio', models.CharField(max_length=10)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.estado_hora')),
            ],
        ),
        migrations.CreateModel(
            name='peluqueros',
            fields=[
                ('rut_usuario', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('id_usuario_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id_servicios', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('duracion_aproximada', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva_r', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cliente_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.cliente')),
                ('id_estado_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.estado_reserva')),
                ('id_fecha_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.fecha')),
                ('id_hora_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.horas_peluqueria')),
                ('id_peluquero_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.peluqueros')),
                ('id_servicio_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.servicios')),
            ],
        ),
        migrations.CreateModel(
            name='peluqueros_servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_servicios_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.servicios')),
                ('rut_usuario_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.peluqueros')),
            ],
        ),
        migrations.CreateModel(
            name='peluquero_horas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fecha_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.fecha')),
                ('id_horas_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.horas_peluqueria')),
                ('id_peluquero_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peluqueria.peluqueros')),
            ],
        ),
    ]
