# Generated by Django 3.0.10 on 2020-11-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0004_servicios_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='precio',
            new_name='precio_servicio',
        ),
    ]
