# Generated by Django 3.0.6 on 2020-11-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0005_auto_20201102_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
