# Generated by Django 3.0.6 on 2020-11-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0009_auto_20201112_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
