# Generated by Django 3.0.6 on 2020-11-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0010_auto_20201112_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
