# Generated by Django 3.0.6 on 2020-11-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0011_auto_20201112_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='id_fecha',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
