# Generated by Django 3.0.6 on 2020-11-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peluqueria', '0012_auto_20201119_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id_reserva_r',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
